### ISSUE TITLE
Zip file recognized as docx

### ISSUE THREAD

**Issue by zsbodnar** [AJMitev/FileTypeChecker#24]
Zip file is recognized as docx file and also IsArchive() returns false.

**To Reproduce**
1. Please use the attached zip file

**Expected behavior**
The file is recognized as zip archive.

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version: nuget v3.0.0

[01-starting-setup.zip](https://github.com/AJMitev/FileTypeChecker/files/10944500/01-starting-setup.zip)

**Comment by Trimack93** [comment]
Looks like library is finding two matching types on ZIP files:

- "Microsoft Office 365 Document" with magic numbers "0x50, 0x4B, 0x03, 0x04, 0x14"
- "ZIP file" with magic numbers "0x50, 0x4B, 0x03, 0x04"

Because number of matching bytes in Office document is higher than in ZIP file, library is wrongly assuming that provided file has .docx type.

From what I see, it should be already fixed in [this pull request](https://github.com/AJMitev/FileTypeChecker/pull/22). Is there any eta on new library release? 🙂

**Comment by AJMitev** [comment]
I am on a very buy schedule so far but I am planning to release the new version in coming weeks till the end of this month.

**Comment by AJMitev** [comment]
You can download an updated version from [nuget](https://www.nuget.org/packages/File.TypeChecker/4.0.0)
