### ISSUE TITLE
Ms Office files is more then docx

### ISSUE THREAD

**Issue by vsuchan** [AJMitev/FileTypeChecker#32]
The problem I see is that if I send an Excel file with an "**xlsx**" extension, it returns as a filetype. Extension "**docx**" this can cause an error. I understand that the magic bytes are the same, but the extension is not.

**Comment by AJMitev** [comment]
You are not obligated to use "Extension" property from the result. The main goal here is to validate the type/container of the file and to protect yourself from invalid type/container. Since we cannot differentiate xlsx and docx from each other it is indifferent if the result contains one extension which is not right 50% of the time or if it contains an array of all possible extensions. 

I hope this makes sense to you and If you have any suggestions how to solve that I will be more than happy to see it.

**Comment by miwojtkiewicz** [comment]
Can I reopen this? I'm not sure what the best direction is for office files. My code is checking the extension of the file, but the validator will throw an error because the file types have matching sequences. You said in March that we're not obligated to use the Extension property, but you also throw an error if it's null. So what's the best route if I want to validate office / zip files that will all have the same sequence?
